### ISSUE TITLE
Dependency injection 

### ISSUE THREAD

**Issue by tajnymag** [KasheK420/VSB-BOT-Vratny#30]
Používáme hodně servis a propojujeme je přes globální instance. Co použít dependency injection? 

https://github.com/microsoft/tsyringe

**Comment by Cloudy71** [comment]
Nevidím moc důvod proč to používat. Ale pokud se ti chce házet čas do přepisování, tak klidně do toho, ale nevím jak se to udrží aktuální, když se musí brzy doplňovat další featury. Vznikne potom mnoho konfliktů a mně se to nechce řešit. Ke všemu toto je moc spring-type dependency framework, a akorát to z toho udělá bloat.

EDIT: Nad tímto by se spíše má přemýšlet v nových projektech, pokud nějaké budou. Tento bot byl psaný v době ještě na nějaký studentský VŠB dc a nijak mě tu nikdo neplatí za to, abych psal quality sw (Proto taky update ode mě trvá klidně i měsíc), tak jsem se moc neobtěžoval s component systemem. Proto taky hlavně doufám, že to brzy někdo převezme za mě abych se o to nemusel moc starat.

**Comment by tajnymag** [comment]
Ok. Mně právě přišlo, že je celý bot psaný java stylem, tak už mi tam ta injekce dávala smysl.

Nechuti ale rozumím a nechávám to tedy být. Přepis bych klidně udělal, ale pokud by tohle byl názor jen můj, smysl by chyběl.

(Issue zatím nechám otevřené, ať se mají ještě šanci ostatní vyjádřit. Uzavřu ho tak za týden.)
